all:
#	/opt/rocm/hip/bin/hipcc -I/opt/rocm/include  -L/opt/rocm/rocblas/lib  -lrocblas -L/usr/lib/atlas-base/atlas/  -lblas  -o amd_trsm_reduce amd_trsm_reduce.cpp
	/opt/rocm/hip/bin/hipcc -I/opt/rocm/include  -L/opt/rocm/rocblas/lib  -lrocblas -L/usr/lib/atlas-base/atlas/  -lblas  -o amd_trsm amd_trsm.cpp
#apt-get install libatlas-base-dev
